name: CI

on:
  push:
    branches: [ master ]

  pull_request:

  workflow_dispatch:

env:
  BIC_VERSION: 1.0.0

# Decouple building from deploying
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: mtime
        run: sudo apt install git-restore-mtime && git restore-mtime

      - name: chmod
        run: chmod 777 .

      - name: Build
        run: docker run --rm -v "$PWD":/src ghcr.io/pinjasaur/bic:$BIC_VERSION

      - name: chown
        run: echo "$(whoami):$(id -gn)" | xargs -I {} sudo chown -R {} build

      - uses: actions/setup-node@v4
        with:
          node-version: 20 # current LTS

      - name: Index
        run: npx -y pagefind --site build

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    # Limit deploying
    if: github.head_ref == 'master'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: demo.bic.sh
